sname: app_environment
channels:
  - snowflake
dependencies:
  - python=3.10.*
  - snowflake-ml-python
  - getpass4
  - scikit-learn
  - matplotlib=*
  - pillow=*
  - pytorch=*
  - torchvision=*
  - snowflake-ml-python=*
